-- Create the table for storing URLs
CREATE TABLE IF NOT EXISTS public.urls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  original_url text NOT NULL,
  short_code text NOT NULL,
  click_count integer DEFAULT 0 NOT NULL,
  custom_alias text -- optional, can be same as short_code or separate if we want to distinguish generated vs custom
);

-- Add unique constraint on short_code to prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS urls_short_code_idx ON public.urls (short_code);

-- Enable Row Level Security (RLS) - Recommended for security
ALTER TABLE public.urls ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read URLs (for redirection)
CREATE POLICY "Enable read access for all users" ON public.urls
  FOR SELECT USING (true);

-- Create a policy that allows anyone to insert URLs (public shortener)
-- Ideally this should be rate limited or authenticated, but for MVP open is fine.
CREATE POLICY "Enable insert access for all users" ON public.urls
  FOR INSERT WITH CHECK (true);

-- Create a policy that allows updating click counts (this might need service role if using client)
-- For the click increment, we'll likely use a stored procedure or the service role API.
-- Just in case, allow update for now (in production, lock this down).
CREATE POLICY "Enable update for all users" ON public.urls
  FOR UPDATE USING (true);
  
-- Create a helper function to increment click count safely (atomic update)
CREATE OR REPLACE FUNCTION increment_click_count(code text)
RETURNS void AS $$
BEGIN
  UPDATE public.urls
  SET click_count = click_count + 1
  WHERE short_code = code;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Seed data for testing
INSERT INTO public.urls (original_url, short_code, click_count)
VALUES 
  ('https://google.com', 'google', 0),
  ('https://github.com', 'github', 10),
  ('https://vercel.com', 'vercel', 5)
ON CONFLICT (short_code) DO NOTHING;
